name: AU-TO
on:
  schedule:
    - cron: '30 5 1 * *'
  workflow_dispatch:
jobs:
  build1:
    name: 'NO ROOT...'
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Run code
        env:
          VERSION: 'Default'
          DEVICE: 'arm64-v8a'
          ICONS: 'true'
          OPTIMIZATION: 'true'
          AMOLED: 'true'
          FEATURE: 'always-autorepeat hide-autoplay-button'
          ROUND: 'true'
          TYPE: 'true'
          SHORTS: 'true'
          CREATE: 'true'

        run: |
          # kakathic
          . .github/install.sh

  build2:
    name: 'ROOT...'
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Run code
        env:
          VERSION: 'Default'
          DEVICE: 'arm64-v8a'
          ICONS: 'true'
          OPTIMIZATION: 'true'
          AMOLED: 'true'
          FEATURE: 'always-autorepeat hide-autoplay-button '
          ROUND: 'true'
          TYPE: 'false'
          SHORTS: 'true'
          CREATE: 'true'

        run: |
          # kakathic
          . .github/install.sh

  build3:
    name: 'AMOLED NO ROOT...'
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Run code
        env:
          VERSION: 'Default'
          DEVICE: 'arm64-v8a'
          ICONS: 'true'
          OPTIMIZATION: 'true'
          AMOLED: 'false'
          FEATURE: 'always-autorepeat hide-autoplay-button'
          ROUND: 'true'
          TYPE: 'true'
          SHORTS: 'true'
          CREATE: 'true'

        run: |
          # kakathic
          . .github/install.sh

  build4:
    name: 'AMOLED ROOT...'
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Run code
        env:
          VERSION: 'Default'
          DEVICE: 'arm64-v8a'
          ICONS: 'true'
          OPTIMIZATION: 'true'
          AMOLED: 'false'
          FEATURE: 'always-autorepeat hide-autoplay-button '
          ROUND: 'true'
          TYPE: 'false'
          SHORTS: 'true'
          CREATE: 'true'

        run: |
          # kakathic
          . .github/install.sh

  build5:
    name: 'Upload...'
    runs-on: ubuntu-22.04
    needs:
      - build1
      - build2
      - build3
      - build4
    steps:
      - uses: actions/checkout@v3
      - name: Upload json
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ github.token }}
          name: Update
          tag_name: Up
          files: Up*.json
          prerelease: true
      - name: Upload File
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ github.token }}
          name: YT-AT
          tag_name: Vip
          files: Up/*
