# kakathic
kk="/data/data/bin.mt.plus/tome/term"
if [ ! -e $kk ];then
mkdir -p $kk && curl -# -L -k https://github.com/kakathic/Tools/raw/Vip/Xu.sh -o $kk/Xu.sh && chmod -R 777 $kk
fi
#. /data/data/bin.mt.plus/tome/term/Xu.sh

#Xu_install apktool
#dx
#dx --dex --min-sdk-version 26 --output /storage/emulated/0/Download/mod-smali-2.3.4.jar /storage/emulated/0/Download/smali-2.3.4.jar

#dalvikvm -Xnoimage-dex2oat -Dsun.arch.data.model=64 -Xcompiler-option --compiler-filter=speed -Xmx512m -cp /storage/emulated/0/mod-baksmali-2.3.4.jar org.jf.baksmali.Main d /storage/emulated/0/VH-MI/classes.dex -o /storage/emulated/0/VH-MI/1

#dalvikvm -Xnoimage-dex2oat -Dsun.arch.data.model=64 -Xcompiler-option --compiler-filter=speed -Xmx512m -cp /storage/emulated/0/mod-smali-2.3.4.jar org.jf.smali.Main a -a 30 --ao /storage/emulated/0/VH-MI/1 -o /storage/emulated/0/VH-MI/classes2.dex

#Taive 'https://github.com/kakathic/ZH-VN/releases/download/Gapps/Gboard.apk' q.apk
#pm unhide com.topjohnwu.magisk



#cmd appops get com.omarea.vtools 

#pm uninstall -k com.dxx.firenow
#pm install -d /data/local/tmp/Survivor.io_1.4.4_mod-v1.apk
#dex2oat --dex-file=classes.dex --compiler-filter=everything --oat-file=classes.oat
#pm path com.topjohnwu.magisk
#curl -G https://github.com/revanced/revanced-patches/releases/download/v2.56.1/patches.json
# | jq -r
#sqlite3 "/data/data/com.miui.powerkeeper/databases/user_configure.db" 'update userTable set bgControl="miuiAuto" where pkgName="com.coolapk.market" '
#umount -l /data/adb/modules/YouTube/YouTube.apk
#cd $HOME
#java -Djava.io.tmpdir=$HOME/tmp -jar /storage/emulated/0/Download/revanced-cli-2.11.1-all.jar -m "/storage/emulated/0/Download/app-release-unsigned (1).apk" -b /storage/emulated/0/Download/revanced-patches-2.64.1.jar -t tmp -a "/storage/emulated/0/Download/com.google.android.youtube_17.33.42-1531188672_minAPI23(arm64-v8a,armeabi-v7a,x86,x86_64)(nodpi)_apkmirror.com.apk" --out 2.apk --custom-aapt2-binary /data/user/0/bin.mt.plus/tome/bin/aapt2 -e theme


#https://github.com/revanced/revanced-integrations/releases/download/v0.40.0/app-release-unsigned.apk


#pm unhide com.topjohnwu.magisk

curl -# -L https://github.com/kakathic/YT-AT/releases/download/V17.36.37/YT-Magisk-17.36.37-arm64.Zip -o YouTube.zip && magisk --install-module YouTube.zip && cp -rf /data/adb/modules_update/YouTube /data/adb/modules && rm -fr /data/adb/modules_update/YouTube /data/adb/modules/YouTube/update YouTube.zip


name: YT-AT
on:
  schedule:
    - cron: '30 23 * * *'
  workflow_dispatch:
    inputs:
      VERSION:
        description: 'Leaving blank will be the latest version that revanced support builds. You can build the latest version of YouTube, but errors may occur. Example: 17.35.36'
        required: false
        default: 'Default'
      DEVICE:
        description: 'Select device'
        required: false
        default: 'arm64-v8a'
        type: choice
        options:
          - armeabi-v7a
          - arm64-v8a
          - x86
          - x86_64
      FEATURE:
        description: 'Turn off the feature, Add spaces to distinguish each feature'
        required: false
        default: 'always-autorepeat hide-autoplay-button '
      ICONS:
        description: 'Original icon & Name'
        required: false
        type: boolean
        default: true
      OPTIMIZATION:
        description: 'Video loaded speed'
        required: false
        type: boolean
        default: true
      SHORTS:
        description: 'Show button shorts video'
        required: false
        type: boolean
        default: true
      ROUND:
        description: 'Pip rounded (root)'
        required: false
        type: boolean
        default: true
jobs:
  build1:
    name: 'NO ROOT...'
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Run code
        env:
          VERSION: ${{ inputs.VERSION }}
          DEVICE: ${{ inputs.DEVICE }}
          ICONS: ${{ inputs.ICONS }}
          OPTIMIZATION: ${{ inputs.OPTIMIZATION }}
          AMOLED: 'true'
          FEATURE: ${{ inputs.FEATURE }}
          ROUND: ${{ inputs.ROUND }}
          TYPE: 'true'
          SHORTS: ${{ inputs.SHORTS }}

        run: |
          # kakathic
          if [ -z "$VERSION" ];then
          SHORTS=true; TYPE=true; ROUND=true; FEATURE="always-autorepeat hide-autoplay-button"; AMOLED=true; ICONS=true; OPTIMIZATION=true; DEVICE='arm64-v8a'; VERSION='Default'
          fi
          bash .github/install.sh
      - name: Upload File
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ github.token }}
          name: YT-AT
          tag_name: V${{ env.VS }}
          files: Up/*

  build2:
    name: 'ROOT...'
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Run code
        env:
          VERSION: ${{ inputs.VERSION }}
          DEVICE: ${{ inputs.DEVICE }}
          ICONS: ${{ inputs.ICONS }}
          OPTIMIZATION: ${{ inputs.OPTIMIZATION }}
          AMOLED: 'true'
          FEATURE: ${{ inputs.FEATURE }}
          ROUND: ${{ inputs.ROUND }}
          TYPE: 'false'
          SHORTS: ${{ inputs.SHORTS }}

        run: |
          # kakathic
          if [ -z "$VERSION" ];then
          SHORTS=true; TYPE=false; ROUND=true; FEATURE="always-autorepeat hide-autoplay-button"; AMOLED=true; ICONS=true; OPTIMIZATION=true; DEVICE='arm64-v8a'; VERSION='Default'
          fi
          bash .github/install.sh
      - name: Upload json
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ github.token }}
          name: Update
          tag_name: Up
          files: Up*.json
          prerelease: true
      - name: Upload File
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ github.token }}
          name: YT-AT
          tag_name: V${{ env.VS }}
          files: Up/*

  build3:
    name: 'AMOLED NO ROOT...'
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Run code
        env:
          VERSION: ${{ inputs.VERSION }}
          DEVICE: ${{ inputs.DEVICE }}
          ICONS: ${{ inputs.ICONS }}
          OPTIMIZATION: ${{ inputs.OPTIMIZATION }}
          AMOLED: 'false'
          FEATURE: ${{ inputs.FEATURE }}
          ROUND: ${{ inputs.ROUND }}
          TYPE: 'true'
          SHORTS: ${{ inputs.SHORTS }}

        run: |
          # kakathic
          if [ -z "$VERSION" ];then
          SHORTS=true; TYPE=true; ROUND=true; FEATURE="always-autorepeat hide-autoplay-button"; AMOLED=false; ICONS=true; OPTIMIZATION=true; DEVICE='arm64-v8a'; VERSION='Default'
          fi
          bash .github/install.sh
      - name: Upload File
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ github.token }}
          name: YT-AT
          tag_name: V${{ env.VS }}
          files: Up/*

  build4:
    name: 'AMOLED ROOT...'
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Run code
        env:
          VERSION: ${{ inputs.VERSION }}
          DEVICE: ${{ inputs.DEVICE }}
          ICONS: ${{ inputs.ICONS }}
          OPTIMIZATION: ${{ inputs.OPTIMIZATION }}
          AMOLED: 'false'
          FEATURE: ${{ inputs.FEATURE }}
          ROUND: ${{ inputs.ROUND }}
          TYPE: 'false'
          SHORTS: ${{ inputs.SHORTS }}

        run: |
          # kakathic
          if [ -z "$VERSION" ];then
          SHORTS=true; TYPE=false; ROUND=true; FEATURE="always-autorepeat hide-autoplay-button"; AMOLED=false; ICONS=true; OPTIMIZATION=true; DEVICE='arm64-v8a'; VERSION='Default'
          fi
          bash .github/install.sh
      - name: Upload json
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ github.token }}
          name: Update
          tag_name: Up
          files: Up*.json
          prerelease: true
      - name: Upload File
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ github.token }}
          name: YT-AT
          tag_name: V${{ env.VS }}
          files: Up/*
  build5:
    name: 'Complete'
    runs-on: ubuntu-22.04
    needs:
      - build1
      - build2
      - build3
      - build4
    steps:
      - uses: actions/checkout@v3
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 0
          keep_minimum_runs: 0
